<div class="no-contact-main-div">
    <h3>
        <?php echo __($block->getTitle()) ?>
    </h3>
    <p>
        <?php echo __($block->getDescription()) ?>
    </p>
</div>
<style>
    .no-contact-main-div h3 {
        font-size: 16px;
        font-weight: bold;
        margin-top: 0;
    }
    .no-contact-main-div p {
        font-size: 15px;
        margin-bottom: 0;
    }
    .no-contact-main-div {
         padding: 20px;
         border: 1px solid;
     }
</style>