<?php if ($comment = $block->getOrderComment()): ?>
    <div class="block block-order-details-view">
        <div class="block-content">
            <div class="box box-order-comment">
                <strong class="box-title"><span><?php /* @escapeNotVerified */
                        echo __('Contactless Delivery') ?></span></strong>
                <div class="box-content">
                    <?php echo $block->getOrderCommentHtml(); ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>